default_install_hook_types: [pre-commit, commit-msg]
default_stages: [commit]

repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
        - id: forbid-tabs
          exclude: "(setup.cfg|.git/)"
        - id: remove-tabs
          exclude: "(setup.cfg|.git/)"
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    - id: detect-secrets
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-case-conflict
      - id: check-ast
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint
        args: [--ignore, CHANGELOG.md]
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 5.11.4
    hooks:
      - id: isort
  - repo: https://github.com/terrencepreilly/darglint
    rev: "v1.8.1"
    hooks:
        - id: darglint
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.0
    hooks:
    - id: python-safety-dependencies-check
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.39.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
